"""add user_role_presets

Revision ID: 0bb60d8aabca
Revises: e4e8f0e553b1
Create Date: 2026-04-10 10:04:10.623098
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0bb60d8aabca'
down_revision: Union[str, None] = 'e4e8f0e553b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
