"""add impact_scope and jira_fields_pending

Revision ID: e4e8f0e553b1
Revises: 
Create Date: 2026-04-10 09:02:28.749045
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'e4e8f0e553b1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('impact_scope', sa.Text(), nullable=True))
    op.add_column('issues', sa.Column('jira_fields_pending', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'jira_fields_pending')
    op.drop_column('issues', 'impact_scope')
    # ### end Alembic commands ###
